Traceback (most recent call last):
  File "/home/tiagoburiol/.local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/tiagoburiol/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiagoburiol/anaconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiagoburiol/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tiagoburiol/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/tiagoburiol/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/tiagoburiol/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xp = np.linspace(xi[0], xi[-1])
yp = []
for x in xp:
    y = calculaP(x, xi, yi)
    yp.append(y)

plt.plot(xi, yi, 'o', xp, yp,'-',color='black')
plt.grid()
plt.show()

print ("P(",0.9,") =", calculaP(0.9, xi,yi))

plt.savefig('figura_3.3a.png', dpi=300)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[6], line 4[0m
[1;32m      2[0m yp [38;5;241m=[39m []
[1;32m      3[0m [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m xp:
[0;32m----> 4[0m     y [38;5;241m=[39m calculaP(x, xi, yi)
[1;32m      5[0m     yp[38;5;241m.[39mappend(y)
[1;32m      7[0m plt[38;5;241m.[39mplot(xi, yi, [38;5;124m'[39m[38;5;124mo[39m[38;5;124m'[39m, xp, yp,[38;5;124m'[39m[38;5;124m-[39m[38;5;124m'[39m,color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mblack[39m[38;5;124m'[39m)

Cell [0;32mIn[5], line 8[0m, in [0;36mcalculaP[0;34m(x, X, Y)[0m
[1;32m      6[0m         [38;5;28;01mif[39;00m k [38;5;241m!=[39m i:
[1;32m      7[0m             lk [38;5;241m=[39m lk[38;5;241m*[39m(x [38;5;241m-[39m X[i])[38;5;241m/[39m(X[k][38;5;241m-[39mX[i])
[0;32m----> 8[0m     valor [38;5;241m=[39m valor [38;5;241m+[39m Y[k][38;5;241m*[39mlk 
[1;32m      9[0m [38;5;28;01mreturn[39;00m valor

[0;31mIndexError[0m: index 4 is out of bounds for axis 0 with size 4

